openapi: 3.0.0
info:
  title: Train API
  version: 1.0.0
  description: API for station suggestions, departures, arrivals, and board info.
servers:
  - url: http://localhost:3000
    description: Local server
paths:
  /api/stations/autocomplete:
    get:
      summary: Autocomplete stations by name.
      parameters:
        - in: query
          name: q
          schema:
            type: string
          required: true
          description: Search query for station name.
        - in: query
          name: limit
          schema:
            type: integer
          required: false
          description: Max number of results (default 5).
      responses:
        '200':
          description: List of matching stations.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    latitude:
                      type: number
                    longitude:
                      type: number
  /api/stations/{stationId}/departures:
    get:
      summary: Get upcoming train departures for a specific station
      parameters:
        - in: path
          name: stationId
          schema:
            type: string
          required: true
          description: The station EVA ID (e.g., 8000261 for München Hbf)
        - in: query
          name: minutes
          schema:
            type: integer
            default: 10
          required: false
          description: Minutes ahead to show departures for (default 10)
      responses:
        '200':
          description: Array of departure objects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    tripId:
                      type: string
                    when:
                      type: string
                      format: date-time
                    plannedWhen:
                      type: string
                      format: date-time
                    delay:
                      type: integer
                      nullable: true
                    platform:
                      type: string
                      nullable: true
                    direction:
                      type: string
                    line:
                      type: object
                      properties:
                        name:
                          type: string
                        productName:
                          type: string
                    stop:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
  /api/stations/{stationId}/arrivals:
    get:
      summary: Get upcoming train arrivals for a specific station
      description: Returns a list of arrivals at the given station for the next N minutes.
      parameters:
        - in: path
          name: stationId
          schema:
            type: string
          required: true
          description: The EVA (Bahnhof) station ID (e.g., 8089165)
        - in: query
          name: minutes
          schema:
            type: integer
            default: 10
          required: false
          description: Minutes ahead to show arrivals for (default 10)
      responses:
        '200':
          description: Array of arrivals
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    tripId:
                      type: string
                    when:
                      type: string
                    plannedWhen:
                      type: string
        '400':
          description: Missing or invalid stationId
        '500':
          description: Server or upstream error
  /api/stations/{stationId}/board:
    get:
      summary: Get departures and arrivals for a specific station
      description: Returns both departures and arrivals for the given station ID, useful for station boards.
      parameters:
        - in: path
          name: stationId
          schema:
            type: string
          required: true
          description: The station EVA ID (e.g., 8000261 for München Hbf)
        - in: query
          name: minutes
          schema:
            type: integer
            default: 10
          required: false
          description: Minutes ahead to show departures and arrivals for (default 10)
      responses:
        '200':
          description: Object containing arrays of departures and arrivals
          content:
            application/json:
              schema:
                type: object
                properties:
                  departures:
                    type: array
                    items:
                      type: object
                      properties:
                        tripId:
                          type: string
                        when:
                          type: string
                          format: date-time
                        plannedWhen:
                          type: string
                          format: date-time
                        delay:
                          type: integer
                          nullable: true
                        platform:
                          type: string
                          nullable: true
                        direction:
                          type: string
                        line:
                          type: object
                          properties:
                            name:
                              type: string
                            productName:
                              type: string
                        stop:
                          type: object
                          properties:
                            id:
                              type: string
                            name:
                              type: string
                  arrivals:
                    type: array
                    items:
                      type: object
                      properties:
                        tripId:
                          type: string
                        when:
                          type: string
                          format: date-time
                        plannedWhen:
                          type: string
                          format: date-time
                        delay:
                          type: integer
                          nullable: true
                        platform:
                          type: string
                          nullable: true
                        direction:
                          type: string
                        line:
                          type: object
                          properties:
                            name:
                              type: string
                            productName:
                              type: string
                        stop:
                          type: object
                          properties:
                            id:
                              type: string
                            name:
                              type: string
        '400':
          description: Missing or invalid stationId
        '500':
          description: Server or upstream error
  /api/stations/name/{stationName}/board:
    get:
      summary: Get departures and arrivals for a specific station by name
      description: |
        Returns both departures and arrivals for the first station matching the given name (fuzzy search). Useful for boards when the station EVA ID is unknown.
      parameters:
        - in: path
          name: stationName
          schema:
            type: string
          required: true
          description: Full or partial station name (e.g., "München Hbf")
        - in: query
          name: minutes
          schema:
            type: integer
            default: 10
          required: false
          description: Minutes ahead to show departures and arrivals for (default 10)
      responses:
        '200':
          description: Object containing arrays of departures and arrivals
          content:
            application/json:
              schema:
                type: object
                properties:
                  departures:
                    type: array
                    items:
                      type: object
                      properties:
                        time:
                          type: string
                          description: Formatted local time (e.g. "29.07.2025 um 13:55")
                        delay:
                          type: integer
                          nullable: true
                          description: Delay in seconds
                        platform:
                          type: string
                          nullable: true
                        plannedPlatform:
                          type: string
                          nullable: true
                        direction:
                          type: string
                        provenance:
                          type: string
                          nullable: true
                        lineName:
                          type: string
                        productName:
                          type: string
                        operator:
                          type: string
                        destination:
                          type: object
                          nullable: true
                          properties:
                            id:
                              type: string
                            name:
                              type: string
                            type:
                              type: string
                            location:
                              type: object
                              properties:
                                id:
                                  type: string
                                type:
                                  type: string
                                latitude:
                                  type: number
                                longitude:
                                  type: number
                  arrivals:
                    type: array
                    items:
                      type: object
                      properties:
                        time:
                          type: string
                          description: Formatted local time
                        delay:
                          type: integer
                          nullable: true
                        platform:
                          type: string
                          nullable: true
                        plannedPlatform:
                          type: string
                          nullable: true
                        direction:
                          type: string
                        provenance:
                          type: string
                          nullable: true
                        lineName:
                          type: string
                        productName:
                          type: string
                        operator:
                          type: string
                        origin:
                          type: object
                          nullable: true
                          properties:
                            id:
                              type: string
                            name:
                              type: string
                            type:
                              type: string
                            location:
                              type: object
                              properties:
                                id:
                                  type: string
                                type:
                                  type: string
                                latitude:
                                  type: number
                                longitude:
                                  type: number
        '400':
          description: Missing or invalid stationName
        '404':
          description: Station not found
        '500':
          description: Server or upstream error
components: {}
tags: []