openapi: 3.0.0
info:
  title: Train App API
  version: 1.0.0
  description: REST API for station search, departures, arrivals, and station board info.
servers:
  - url: http://localhost:3000
    description: Local server
tags:
  - name: Stations
    description: Operations related to train stations
paths:
  /api/stations/autocomplete:
    get:
      summary: Autocomplete stations by name
      tags:
        - Stations
      parameters:
        - in: query
          name: q
          schema:
            type: string
          required: true
          description: Search query for station name
          example: "Berlin"
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 50
          description: Max number of results (default 25)
          example: 10
      responses:
        "200":
          description: List of matching stations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Station"
              example:
                - id: "8011160"
                  name: "Berlin Hbf"
                - id: "8010255"
                  name: "Berlin Ostbahnhof"
  /api/stations/{stationId}/board:
    get:
      summary: Get departures and arrivals for a specific station
      tags:
        - Stations
      parameters:
        - in: path
          name: stationId
          schema:
            type: string
          required: true
          description: The station EVA ID (e.g., 8000261 for M端nchen Hbf)
          example: "8000261"
        - in: query
          name: minutes
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 60
          description: Minutes ahead to show departures and arrivals for (default 10)
          example: 30
      responses:
        "200":
          description: Object containing arrays of departures and arrivals
          content:
            application/json:
              schema:
                type: object
                properties:
                  departures:
                    type: array
                    items:
                      $ref: "#/components/schemas/Departure"
                  arrivals:
                    type: array
                    items:
                      $ref: "#/components/schemas/Arrival"
              example:
                departures:
                  - tripId: "1|12345|0|80|20231015"
                    when: "2023-10-15T14:35:00+02:00"
                    plannedWhen: "2023-10-15T14:30:00+02:00"
                    delay: 300
                    cancelled: false
                    platform: "11"
                    direction: "Hamburg Hbf"
                    provenance: "M端nchen Hbf"
                    line:
                      name: "ICE 703"
                      productName: "ICE"
                arrivals:
                  - tripId: "1|12346|0|80|20231015"
                    plannedWhen: "2023-10-15T15:10:00+02:00"
                    delay: 60
                    cancelled: false
                    platform: "7"
                    direction: "Berlin Hbf"
                    provenance: "Frankfurt(Main) Hbf"
                    line:
                      name: "IC 2046"
                      productName: "IC"
components:
  schemas:
    Station:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          description: The unique EVA ID of the station
          example: "8000261"
        name:
          type: string
          description: The full name of the station
          example: "M端nchen Hbf"
    Departure:
      type: object
      required:
        - tripId
        - plannedWhen
        - direction
        - line
      properties:
        tripId:
          type: string
          description: Unique identifier for the trip
          example: "1|12345|0|80|20231015"
        when:
          type: string
          format: date-time
          description: Actual scheduled departure time (including delays)
          example: "2023-10-15T14:35:00+02:00"
        plannedWhen:
          type: string
          format: date-time
          description: Originally planned departure time (without delays)
          example: "2023-10-15T14:30:00+02:00"
        delay:
          type: integer
          nullable: true
          description: Delay in seconds (null if unknown)
          example: 300
        cancelled:
          type: boolean
          description: Whether the departure has been cancelled
          example: false
        platform:
          type: string
          nullable: true
          description: Platform number (null if unknown)
          example: "12"
        direction:
          type: string
          description: Final destination of the trip
          example: "Hamburg Hbf"
        provenance:
          type: string
          description: Station where the train is coming from
          example: "M端nchen Hbf"
        line:
          $ref: "#/components/schemas/Line"
    Arrival:
      type: object
      required:
        - tripId
        - plannedWhen
        - direction
        - line
      properties:
        tripId:
          type: string
          description: Unique identifier for the trip
          example: "1|12346|0|80|20231015"
        when:
          type: string
          format: date-time
          description: Actual scheduled arrival time (including delays)
          example: "2023-10-15T15:11:00+02:00"
        plannedWhen:
          type: string
          format: date-time
          description: Originally planned arrival time (without delays)
          example: "2023-10-15T15:10:00+02:00"
        delay:
          type: integer
          nullable: true
          description: Delay in seconds (null if unknown)
          example: 60
        cancelled:
          type: boolean
          description: Whether the arrival has been cancelled
          example: false
        platform:
          type: string
          nullable: true
          description: Platform number (null if unknown)
          example: "7"
        direction:
          type: string
          description: Final destination of the trip
          example: "Berlin Hbf"
        provenance:
          type: string
          description: Station where the train is coming from
          example: "Frankfurt(Main) Hbf"
        line:
          $ref: "#/components/schemas/Line"
    Line:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: The display name of the train line
          example: "ICE 703"
        productName:
          type: string
          description: The type of train (ICE, IC, RE, etc.)
          example: "ICE"
